name: deployer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Build
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cotizaciones .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cotizaciones-binary
        path: cotizaciones

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: cotizaciones-binary
    
    - name: config copy files
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H ${{ secrets.SERVER }} >> ~/.ssh/known_hosts
        
    - name: Deploy to production
      run: |
        echo "${{ secrets.KEY }}" > ./private_key
        chmod 600 ./private_key
        ls -la
        ssh -o StrictHostKeyChecking=no -i ./private_key ${{ secrets.USER }}@${{ secrets.SERVER }} "cd /opt/cotizaciones && rm -rf *"
        ssh -o StrictHostKeyChecking=no -i ./private_key ${{ secrets.USER }}@${{ secrets.SERVER }} "cd /opt/codes/bot-dockers && git pull" 
        scp -o StrictHostKeyChecking=no -i ./private_key -r cotizaciones ${{ secrets.USER }}@${{ secrets.SERVER }}:/opt/cotizaciones/
        ssh -o StrictHostKeyChecking=no -i ./private_key ${{ secrets.USER }}@${{ secrets.SERVER }} "cp /opt/codes/bot-dockers/cotizaciones/docker/cotizaciones.dockerfile /opt/cotizaciones"
        ssh -o StrictHostKeyChecking=no -i ./private_key ${{ secrets.USER }}@${{ secrets.SERVER }} "cd /opt/cotizaciones && ls -la"
        ssh -o StrictHostKeyChecking=no -i ./private_key ${{ secrets.USER }}@${{ secrets.SERVER }} "docker build -t localhost:32000/cotizaciones:latest -f /opt/cotizaciones/cotizaciones.dockerfile /opt/cotizaciones/"
        ssh -o StrictHostKeyChecking=no -i ./private_key ${{ secrets.USER }}@${{ secrets.SERVER }} "docker push localhost:32000/cotizaciones:latest" 
        ssh -o StrictHostKeyChecking=no -i ./private_key ${{ secrets.USER }}@${{ secrets.SERVER }} "microk8s kubectl apply -f /opt/codes/bot-dockers/cotizaciones/kub/services.yaml" 
